### ISSUE TITLE
如果不用gulp，只用webpack会不会更好，感觉应用webpack就可以

### ISSUE THREAD

**Issue by weianzi** [hejianxian/framework7-webpack-demo#1]

**Comment by weianzi** [comment]
去掉了gulp
https://github.com/weianzi/framework7-webpack-demo

**Comment by hejianxian** [comment]
是可以去掉的！我看了你demo里的配置，很棒，学习了！😁😁

**Comment by imac8t** [comment]
求教程哈哈

**Comment by hejianxian** [comment]
@imac8t webpack分支就是了，主要是看webpack.config.js的配置和package.json里的script配置
