### ISSUE TITLE
为啥我运行完 webpack ，没有报错，打开页面找不到f7 

### ISSUE THREAD

**Issue by yczf1836** [hejianxian/framework7-webpack-demo#3]
Cannot find module "framework7"

**Comment by yczf1836** [comment]
还有就是问下 你这个分支 不是说只有 webpack ，怎么还是要gulp运行？不能直接webpack 运行？

**Comment by hejianxian** [comment]
抱歉！文档没写清楚。 如果是gulp+webpack的，是需要bower install 来安装framework7。

如果是分支webpack，是不需要gulp的，直接npm run xx 就可以。在README.md里有描述。
