### ISSUE TITLE
为啥webpack 版本 npm build 没有反应？

### ISSUE THREAD

**Issue by yczf1836** [hejianxian/framework7-webpack-demo#4]
https://github.com/weianzi/framework7-webpack-demo   这个版本git 地址无效  然后，下载后运行npm build  没有反应 ；npm start 是可以的。方便的话，留个 email

**Comment by hejianxian** [comment]
这是webpack分支的地址：git clone -b webpack https://github.com/Alex-fun/framework7-webpack-demo.git

然后 你可以看看package.json配对的script属性是如何运行的。

命令一般都是npm run xx

例如build  对应的是 npm run build，你切换分支后，可以看到README.md文件上是有描述的。
